
obj-y += os_simple.o
obj-y += $(ROOTDIR)/examples/system_hooks.o

inc-y += $(ROOTDIR)/boards/$(BOARDDIR)/$(BDIR)/config
VPATH +=  $(ROOTDIR)/boards/$(BOARDDIR)/$(BDIR)/config

ldcmdfile-y=$(ROOTDIR)/arch/arm/arm_cm3/scripts/linkscript_gcc_lm.ldf
build-exe-y = OpenSAR




